version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

  settings:
    errcheck:
      check-type-assertions: true

issues:
  exclude-use-default: true
